import type { SeedKind } from "./engine/seeds";

export type { SeedKind };

export type Family = "classic" | "glass" | "tiles" | "flow" | "radial" | "iso";

export type Session = {
  id: string;
  name: string;
  tag: string;
  blurb: string;
  preset: string;
  seed: SeedKind;
  family: Family;
  spin?: number;
  /** 0 = still. Most starts omit this. */
  evolve?: number;
};

export const FAMILIES: { id: "all" | Family; label: string }[] = [
  { id: "all", label: "All" },
  { id: "classic", label: "Classic" },
  { id: "glass", label: "Glass" },
  { id: "tiles", label: "Tiles" },
  { id: "flow", label: "Flow" },
  { id: "radial", label: "Radial" },
  { id: "iso", label: "Iso" },
];

/**
 * Board order. The first row is what a visitor sees before scrolling, so it is the
 * starts that hold a bright, deep nest on their own. Keys 1–9 follow this order.
 */
const ORDER = [
  "king-glass",
  "spiral",
  "packed-bloom",
  "kaleid",
  "sierpinski",
  "double-glass",
  "arc-floor",
  "iso-stack",
  "polar-rings",
  "fair-captive",
  "cube-city",
  "insanity",
  "light-hurt",
  "arc-nest",
  "fold-chevrons",
  "many-nests",
  "dragon",
  "four-square",
  "jellyfish",
  "gasket",
  "bloom-hall",
  "snowflake",
  "fern",
  "first-light",
  "drift-field",
];

const BOARD: Session[] = [
  {
    id: "kaleid",
    name: "Kaleid",
    tag: "Six-fold",
    blurb: "Rotational copies stacked on the glass mixer. A mandala that still breathes.",
    preset: "kaleid",
    seed: "sun",
    family: "radial",
    spin: 0.016,
  },
  {
    id: "packed-bloom",
    name: "Packed Bloom",
    tag: "Phyllotaxis",
    blurb: "Vogel spiral packing. Six-fold glass turns a flower into a hall of flowers.",
    preset: "kaleid",
    seed: "bloom",
    family: "radial",
    spin: 0.016,
  },
  {
    id: "insanity",
    name: "Insanity",
    tag: "They make each other",
    blurb: "Loop A writes Loop B writes Loop A. Hard to hold. Glorious when it holds.",
    preset: "insanity",
    seed: "plasma",
    family: "glass",
    spin: 0.022,
  },
  {
    id: "light-hurt",
    name: "Light Hurt",
    tag: "Overdriven",
    blurb: "Delay, hue walk, 24fps stutter. Turn Contrast until it bites.",
    preset: "light-hurt",
    seed: "burst",
    family: "glass",
    spin: 0.014,
  },
  {
    id: "arc-floor",
    name: "Arc Floor",
    tag: "Truchet tiles",
    blurb: "Quarter-arcs on a grid — a 1704 tiling, then folded through glass.",
    preset: "king-glass",
    seed: "arcs",
    family: "tiles",
    spin: 0.016,
  },
  {
    id: "arc-nest",
    name: "Arc Nest",
    tag: "90° fold",
    blurb: "Truchet arcs through 90° glass, scaled small so generations stack.",
    preset: "fold-90",
    seed: "arcs",
    family: "tiles",
    spin: 0.014,
  },
  {
    id: "many-nests",
    name: "Many Nests",
    tag: "PIP in PIP",
    blurb: "Scale so small the 90° fold shows four, five generations at once.",
    preset: "pip-deep",
    seed: "grid",
    family: "glass",
    spin: 0.014,
  },
  {
    id: "double-glass",
    name: "Double Glass",
    tag: "Fractal of fractal",
    blurb: "Loop A writes Loop B writes Loop A. Two nests occupying one picture.",
    preset: "double-glass",
    seed: "arcs",
    family: "glass",
    spin: 0.016,
  },
  {
    id: "sierpinski",
    name: "Sierpiński",
    tag: "120° gasket",
    blurb: "Three copies at 120°, each half size. The holes are the picture.",
    preset: "sierpinski",
    seed: "grid",
    family: "classic",
    spin: 0.012,
  },
  {
    id: "fern",
    name: "Fern",
    tag: "Unequal fold",
    blurb: "A big copy and a small one, leaned aside. Foliage from the glass.",
    preset: "fern",
    seed: "arcs",
    family: "classic",
    spin: 0.012,
  },
  {
    id: "spiral",
    name: "Spiral Nest",
    tag: "Turn and shrink",
    blurb: "Each copy turns and shrinks. A nautilus of nested monitors.",
    preset: "spiral",
    seed: "grid",
    family: "classic",
    spin: 0.014,
  },
  {
    id: "snowflake",
    name: "Snowflake",
    tag: "Six-fold ice",
    blurb: "Six copies at 60°, scaled small so the middle is a hole.",
    preset: "snowflake",
    seed: "chevrons",
    family: "classic",
    spin: 0.012,
  },
  {
    id: "dragon",
    name: "Dragon Fold",
    tag: "45° paper fold",
    blurb: "Two copies at 45°, scaled 1/√2. The dragon is the fold.",
    preset: "dragon",
    seed: "chevrons",
    family: "classic",
    spin: 0.012,
  },
  {
    id: "bloom-hall",
    name: "Bloom Hall",
    tag: "Hall of flowers",
    blurb: "Phyllotaxis into six-fold glass. A flower that contains itself.",
    preset: "mandala",
    seed: "bloom",
    family: "radial",
    spin: 0.016,
  },
  {
    id: "polar-rings",
    name: "Polar Rings",
    tag: "Spokes + rings",
    blurb: "Concentric bands in the middlespace. Drag to walk the tunnel.",
    preset: "polar-tunnel",
    seed: "rings",
    family: "radial",
    spin: 0.016,
    evolve: 0.22,
  },
  {
    id: "jellyfish",
    name: "Jellyfish",
    tag: "Light creatures",
    blurb: "Organic, phosphor-smeared animals. Herd Bright to keep them alive.",
    preset: "jellyfish",
    seed: "burst",
    family: "glass",
    spin: 0.022,
    evolve: 0.2,
  },
  {
    id: "gasket",
    name: "Gasket",
    tag: "Nested Vs",
    blurb: "Three contracted copies of hard chevrons. The gasket is the holes.",
    preset: "gasket",
    seed: "chevrons",
    family: "tiles",
    spin: 0.012,
  },
  {
    id: "fold-chevrons",
    name: "Fold Chevrons",
    tag: "Stacked Vs",
    blurb: "Hard chevrons into nested triangles. Scale down to multiply the folds.",
    preset: "sierpinski",
    seed: "chevrons",
    family: "tiles",
    spin: 0.014,
  },
  {
    id: "cube-city",
    name: "Cube City",
    tag: "Cities in cities",
    blurb: "Isometric cubes through four copies at 90°.",
    preset: "iso-cams",
    seed: "iso",
    family: "iso",
    spin: 0.014,
  },
  {
    id: "iso-stack",
    name: "Iso Stack",
    tag: "Cube city",
    blurb: "Isometric cubes as seed tiles. Glass at 90° stacks cities inside cities.",
    preset: "king-glass",
    seed: "iso",
    family: "iso",
    spin: 0.016,
  },
  {
    id: "four-square",
    name: "Four Square",
    tag: "Four monitors",
    blurb: "Four copies at 90°. A square of squares of squares.",
    preset: "four-square",
    seed: "iso",
    family: "iso",
    spin: 0.014,
  },
  {
    id: "first-light",
    name: "First Light",
    tag: "UCSC 1988",
    blurb: "One loop, one screen, the middlespace. Hue drift like old NTSC.",
    preset: "first-light",
    seed: "sun",
    family: "glass",
    spin: 0.014,
    evolve: 0.24,
  },
  {
    id: "king-glass",
    name: "King Glass",
    tag: "The fractal trick",
    blurb: "Two monitors through 50/50 glass at 90°. Peter King’s 1997 move.",
    preset: "king-glass",
    seed: "grid",
    family: "glass",
    spin: 0.016,
  },
  {
    id: "fair-captive",
    name: "Fair Captive",
    tag: "Trap a picture",
    blurb: "Arm a seed, then Trap. The image leaves the source and lives only in the loop.",
    preset: "fair-captive",
    seed: "portrait",
    family: "glass",
    spin: 0.012,
  },
  {
    id: "drift-field",
    name: "Drift Field",
    tag: "Line weather",
    blurb: "Hash-steered ribbons. Delay and smear turn them into creatures.",
    preset: "drift-flow",
    seed: "drift",
    family: "flow",
    spin: 0.02,
    evolve: 0.22,
  },
];

const rank = (id: string) => {
  const i = ORDER.indexOf(id);
  return i < 0 ? ORDER.length : i;
};
export const SESSIONS: Session[] = [...BOARD].sort((a, b) => rank(a.id) - rank(b.id));

export const B3 = {
  home: "https://buildbeyondbelief.com/",
  book: "https://buildbeyondbelief.com/book",
  fit: "https://buildbeyondbelief.com/fit-call",
  blair: "https://www.thelightherder.com/",
  king: "https://sweetandfizzy.com/fractals/",
  portfolio: "https://davidblairportfolio.com/video-feedback-kinetic-sculpture/",
  shapes: "https://bookofshapes.com/",
};
